#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

npx lint-staged
node misc/scripts/syncStrapiMedia.js # Sync Strapi media files to public folder

for i in {1..3}; do
  printf "[Sync] Strapi Media Data... ${i}s\r"
  sleep 1
done
printf "[Synced] Strapi Media Data...  "

git add public/strapi/uploads/* # Stage the synced media files
